2025-03-18 01:45:49,583 ERROR: Auth failed: Subject must be a string [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 01:49:36,520 ERROR: Auth failed: Subject must be a string [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 01:52:21,193 ERROR: Auth failed: Subject must be a string [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 01:52:46,251 ERROR: Auth failed: Subject must be a string [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 01:58:53,475 ERROR: Auth failed: Subject must be a string [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 02:02:42,629 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:45]
2025-03-18 02:02:42,802 INFO: Permissions and roles initialized successfully. [in /Users/mcc/Documents/Develop/backup/sgha/backend/models/user.py:151]
2025-03-18 02:02:42,802 INFO: Permisos y roles inicializados correctamente [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-18 02:05:25,892 ERROR: Auth failed: Subject must be a string [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 09:28:02,558 ERROR: Auth failed: Signature verification failed [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 09:30:47,046 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 09:30:57,407 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 09:31:53,662 ERROR: Auth failed: Signature verification failed [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 09:32:29,550 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 09:33:52,571 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 09:34:12,640 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:150]
2025-03-18 09:49:53,245 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:47]
2025-03-18 09:49:53,666 INFO: Permissions and roles initialized successfully. [in /Users/mcc/Documents/Develop/backup/sgha/backend/models/user.py:151]
2025-03-18 09:49:53,667 INFO: Permisos y roles inicializados correctamente [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:62]
2025-03-18 09:50:45,759 ERROR: Auth failed: Subject must be a string [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:152]
2025-03-18 09:50:55,414 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:152]
2025-03-18 09:50:59,576 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:152]
2025-03-18 09:54:03,276 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:50]
2025-03-18 09:54:03,481 INFO: Permissions and roles initialized successfully. [in /Users/mcc/Documents/Develop/backup/sgha/backend/models/user.py:151]
2025-03-18 09:54:03,481 INFO: Permisos y roles inicializados correctamente [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:65]
2025-03-18 09:54:27,602 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:155]
2025-03-18 09:54:30,966 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:155]
2025-03-18 09:54:58,361 ERROR: Auth failed: Subject must be a string [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:155]
2025-03-18 09:59:43,351 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:155]
2025-03-18 10:17:28,331 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:155]
2025-03-18 10:23:14,345 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:49]
2025-03-18 10:23:14,628 INFO: Permissions and roles initialized successfully. [in /Users/mcc/Documents/Develop/backup/sgha/backend/models/user.py:151]
2025-03-18 10:23:14,629 INFO: Permisos y roles inicializados correctamente [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:64]
2025-03-18 10:23:49,561 ERROR: Auth failed: Subject must be a string [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:154]
2025-03-18 10:24:08,896 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:154]
2025-03-18 10:24:11,596 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:154]
2025-03-18 10:24:51,460 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:154]
2025-03-18 10:25:07,774 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:154]
2025-03-18 10:27:19,316 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:49]
2025-03-18 10:27:19,472 INFO: Permissions and roles initialized successfully. [in /Users/mcc/Documents/Develop/backup/sgha/backend/models/user.py:151]
2025-03-18 10:27:19,472 INFO: Permisos y roles inicializados correctamente [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:64]
2025-03-18 10:28:11,539 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:154]
2025-03-18 10:28:20,099 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:154]
2025-03-18 10:28:26,037 ERROR: Auth failed: Invalid crypto padding [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:154]
2025-03-18 10:35:41,619 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:37]
2025-03-18 10:35:41,857 INFO: Permissions and roles initialized successfully. [in /Users/mcc/Documents/Develop/backup/sgha/backend/models/user.py:135]
2025-03-18 10:35:41,857 INFO: Permisos y roles inicializados correctamente [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:51]
2025-03-18 10:36:45,176 ERROR: Exception on /users/profile [GET] [in /Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask_jwt_extended/view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask_jwt_extended/view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask_jwt_extended/view_decorators.py", line 310, in _decode_jwt_from_request
    locations = config.token_location
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask_jwt_extended/config.py", line 44, in token_location
    locations = current_app.config["JWT_TOKEN_LOCATION"]
                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'JWT_TOKEN_LOCATION'
